### ISSUE TITLE
How to pop up like an iOS-style modal box

### ISSUE THREAD

**Issue by itMcdull** [jordy-garcia/tn_bottom_sheet_navigator#2]
thx

**Comment by jordy-garcia** [comment]
At this moment it just supports ModalBottomSheet, but I'll work on a PopUp implementation.
Stay tuned for updates.

**Comment by jordy-garcia** [comment]
@itMcdull I have implemented a TnNavigatorBuilder so you can use the TnNavigation wherever your need it. Here are some examples of how to integrated https://github.com/jordy-garcia/tn_bottom_sheet_navigator?tab=readme-ov-file#custom-implementation-tnnavigatorbuilder

I hope this solves what you were looking for.

**Comment by itMcdull** [comment]
Thanks, this is very helpful

**Comment by itMcdull** [comment]
How to use with Getx，When generating a routes

**Comment by jordy-garcia** [comment]
@itMcdull this is made as a separate navigation, in your project you should have two navigation technologies, the TnNavigator for the pages that should be consumed inside Dialogs or BottomSheets and the pages that are placed in the whole screen, for those "entire pages" you could use GetX, Go Router or whatever library of your preference.

You can try to implement it with GetX by your own using the TnNavigatorBuilder

**Comment by itMcdull** [comment]
Thank you very much, you are a very good open source author, love you
