### ISSUE TITLE
showTnBottomSheetNav does not have a property called params.

### ISSUE THREAD

**Issue by salih1382** [jordy-garcia/tn_bottom_sheet_navigator#3]
hello
Contrary to the explanation given in the document, showTnBottomSheetNav does not have a property called params and it is not possible to send information to the desired page, please fix this problem in the next version. thank you
source:
`
void showTnBottomSheetNav(
    String initialPath, {
    TnBottomSheetSettings? settings,
  }) =>
      showTnBottomSheetNavigator(
        context: this,
        initialPath: initialPath,
        settings: settings ?? const TnBottomSheetSettings(),
      );
`

**Comment by jordy-garcia** [comment]
You're right. I'm working on it and it will be fixed in the release

**Comment by salih1382** [comment]
My problem was solved by just adding the following lines:
`void showTnBottomSheetNav(String initialPath, {
    Map<String, dynamic>? params,
    TnBottomSheetSettings? settings,
  }) =>
      showTnBottomSheetNavigator(
        context: this,
        initialPath: initialPath,
        params: params,
        settings: settings ?? const TnBottomSheetSettings(),
      );`

**Comment by jordy-garcia** [comment]
Yes, exactly that was missing. Thanks for reporting it!

This fix is available in the newer version
